name: redit-saver

# Controls when the workflow will run
on:
  schedule:
    - cron: '0 12 * * *' # runs at 12:00 UTC everyday
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: checkout repo content
        with:
          repository: 'lunarnautics/saved-reddit-posts'
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8.10' # install the python version needed
          
      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install praw reportlab Pillow python-resize-image
          
      - name: Backup Autisticats
        env: 
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
          PASSWORD: ${{ secrets.PASSWORD }}
          SUBREDDIT: ${{ 'Autisticats' }}
        run: |
          cd Autisticats
          python ~/work/saved-reddit-posts/saved-reddit-posts/redditsaver.py
          
      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          #git pull
          git add -A
          git commit -m "update data" -a
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: master  
